# This is a basic workflow to help you get started with Actions

name: CI

env:
   CI: false

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: NPM install cache
        # You may pin to the exact commit or the version.
        # uses: c-hive/gha-npm-cache@914363b842f36de2461089106eb664af7d1fa539
        uses: c-hive/gha-npm-cache@v1
        
      - name: Deploy react app to github pages
        # You may pin to the exact commit or the version.
        # uses: tanwanimohit/deploy-react-to-ghpages@88c048cc9d31f67a792eec8cf9e94c10eb701dd2
        uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
